### ISSUE TITLE
AppImage crash when opening details view

### ISSUE THREAD

**Issue by azubieta** [nomad-desktop/nx-software-center#50]
The [latest](https://github.com/nomad-desktop/nx-software-center/releases/download/continuous/Software_Center-x86_64.AppImage) AppImage exits with segfault when the details view is opened.

**Comment by star-buck** [comment]
It works here fine under 18.04 ubuntu bionic with kde neon:
![screenshot_20180416_194901](https://user-images.githubusercontent.com/840070/38826143-3c7680f6-41af-11e8-9b49-da471528eb09.png)

**Comment by star-buck** [comment]
program doesnt "Run" though

Nor does it integrate program icons into the menu... but this is what appimagelauncher should be used for in combination with this?

**Comment by azubieta** [comment]
The "run" button should work, is that what is not working or just clicking the file at the $HOME/Applications folder ?
Right now it should be integrated whit one of appimaged, appimagelauncher or appimage-desktop-integrations (last one is preferred as it only monitors the $HOME/Application folder)
I'm considering to use from libappimage the "desktop integration" functions, but @probonopd didn't like the idea (https://github.com/nomad-desktop/nx-software-center/issues/13)

**Comment by star-buck** [comment]
I like the Applications folder (though it could look weird with different language like Chinese in home folder?).
General i think we should have one consistent naming and tools and imo do this:

- rebrand appimagetool to appimagebuilder or something like it
- rebrand and merge appimaged + appimagelauncher +appimage-desktop-integrations (+ eventual appimageupdater) = appimagetool that is universal for enduser to install on system to be "appimage-ready"
- rebrand appimagekit as developer toolkit only

What does anyone think?

Having historical all kinds of tools scattered that function half-only or 80% is not good for universal appimage adoption.

**Comment by azubieta** [comment]
Mentioning @TheAssassin to take a look.

**Comment by azubieta** [comment]
About the the "Applications" folder the ideal use case would be to add it to xdg_dirs, so it get translated with xdg-user-dirs-update and Chinese (and other non English speakers) will be happy. But there is already and XDG_DIR_APPLICATIONS which points to /usr/share/applications and ~/.local/share/applications and those are not meant to contain AppImage files but ".desktop"

**Comment by azubieta** [comment]
About the name changes, totally agreed. We need more meaningful names to be explicit about each application purpose.

About the merge of "appimaged + appimagelauncher +appimage-desktop-integrations" all of them implement slightly different workflows.
appimaged: put an AppImage somewhere in your "home"  and your ready to run it.
appimage-desktop-integrations: put an AppImage somewhere in your "applications" dir  and your ready to run it OR try open AppImage (no matter where), give your explicit concern that YOU trust it (right now it's only making it runnable, non runnable applications are considered untrusted and dangerous) and run it (also it give you options to run it in a Sandbox like fire jail)
appimagelauncher: ... @TheAssassin  should write this part

**Comment by azubieta** [comment]
Also I would like to add that we must have the "rename and merge" talk at the appimagekit repo.

**Comment by star-buck** [comment]
Yeah, sure, it just came up here for the two tools doing similar stuff...

**Comment by TheAssassin** [comment]
Regarding https://github.com/nomad-desktop/nx-software-center/issues/13, I would just have this app perform the desktop integration. Using libappimage, it's easy to check whether applications have been integrated already, and when all tools implement this check, then they'll skip already integrated AppImages (although integrating twice is just some overhead, but nothing dangerous).

Regarding any renames, this repository is not the right place to discuss these. If you want to try your luck, you can suggest it in the AppImageKit repository. However, it is _very_ unlike that any of the tools will ever be renamed. There are so many build systems and scripts depending on the tools a change could lead to many broken builds. We sometimes break other people's workflow by accident, but breaking it intentionally could cause a lot of trouble. We don't have a blog or anything where we could make announcements like this. We hardly have the time to document our stuff properly, although we've been planning to work on some exhaustive docs about AppImages and AppImageKit.
Also, I don't see where the problem is with these names (appimagetool is a tool to build and work with AppImages, for instance). The roles of all tools are further documented in the repository. But really, this is not the place to discuss name changes in foreign repositories, the discussion needs to be moved to the right place.

If you want to harmonize some AppImage related tools, @star-buck, I'd start with choosing _one_ folder where to move AppImages to when integrating them. We have `~/Applications`, `~/.bin`, etc., I'd rather choose one of them. I personally like being a little more transparent by using a non-hidden folder, and `~/Applications` seems like a good start. When https://github.com/TheAssassin/AppImageLauncher/issues/18 has been implemented upstream in libappimage's desktop integration, users can just delete AppImages from `~/Applications` for example, which is how AppImages should work.

appimaged is @probonopd's tool, supporting his preferred workflow. Its workflow is pretty different from the other tools mentioned. But it might be extracted from AppImageKit's code base as soon as I get to it. At first, I need to continue and finish AppImageLauncher.

@azubieta and I will soon have a look at each other's project, and discuss the differences and their pros and cons, as we agreed to 3-4 weeks ago.
AppImageLauncher will receive a signature check similar to what @azubieta's tools has already, see https://github.com/TheAssassin/AppImageLauncher/issues/4. As both tools have been developed in Qt with C++, sharing code even shouldn't be too difficult.
We are also going to perform some necessary refactorings, for example we plan to move the signature related code in AppImageUpdate into a separate lib (or even libappimage) so that all projects can make use of it.
But as mentioned above, first, I would like to finish the remaining feature proposals in AppImageLauncher issue tracker. Feel free to comment there, so we can prioritize the important issues.

**Comment by TheAssassin** [comment]
Re. role of AppImageLauncher:
AppImageLauncher is an "interpreter" for AppImages that is always called for newly downloaded AppImages. It intercepts all calls (by using MIME type registration, binfmt support and a few other tricks), and prompts the user whether to integrate the AppImage or run it once. AppImages don't need to be made executable, as AppImageLauncher will take care of this.

**Comment by azubieta** [comment]
I'm closing this issue as it was fixed in c9a0ff3779db5601e0f1f44a0ae770ebf8da1b36
The discussion about AppImageKit should be held in the AppImageKit repos were it belongs.
